### ISSUE TITLE
Create Data Ingestion Pipeline

### ISSUE THREAD

**Issue by iamsiddhantsahu** [sustainableaviation/EcoPyLot#6]
The "data ingestion pipeline" should be built to perform these tasks:

1. Ingest a JSON file, containing parameters (according to the schema defined in https://github.com/sustainableaviation/EcoPyLot/issues/7)
2. Output a 4-dimensional [`xarray`](https://docs.xarray.dev/en/stable/), containing the dimensions (`pax`, `propulsion`, `year`, `parameters`).
3. Output a tuple of data structures, containing the _unique_ values of the 4 dimensions (`pax`, ...) 

In addition, the following utility functionality should be built:

1. Check for input data validity (valid JSON? corresponding to defined schema?)
2. logging outputs in every function, including statistics (eg. `file loaded, read 778 unique parameters`)

> [!NOTE]
> It is useful to think of the 4d `xarray` as a collection of 3d `xarray`s:
> 
> ![xarray](https://github.com/sustainableaviation/EcoPyLot/assets/23102087/6eb1bc29-87bb-45ef-9cd1-0ecb158f89e4)

**Comment by michaelweinold** [comment]
...all functions _must_ include [typing](https://docs.python.org/3/library/typing.html):

```
def myfunc(
  input1: str,
  input2: float
) -> pd.DataFrame:
```

and include extensive docstrings according to [the `numpy` style guide](https://numpydoc.readthedocs.io/en/latest/format.html).
