### ISSUE TITLE
Investigate (Sparse) XArray Sizes depending on Dimensions

### ISSUE THREAD

**Issue by michaelweinold** [sustainableaviation/EcoPyLot#8]
Try:

4 dimensions (eg. `parameter`, `time`, `size`, `prop`)
8 dimensions (eg. `parameter`, `time`, `size`, `prop1`, `prop2`, `prop3`, `prop4`, `prop5`)

and determine size (in memory) and performance when eg. slicing the array.

See also:

 - https://github.com/pydata/xarray/issues/3206
 - https://github.com/pydata/xarray/issues/3213
 - https://github.com/pydata/xarray/discussions/6683

**Comment by michaelweinold** [comment]
@iamsiddhantsahu, until tomorrow (23.01.2024) please investigate:

Currently, the [`carculator`](https://github.com/romainsacchi/carculator/tree/master) ingests data like this:

The input data is formatted in JSON (cf. the [`default_parameters.json`](https://github.com/romainsacchi/carculator/blob/master/carculator/data/default_parameters.json)):

```json
"7-2000-converter mass": {
        "name": "converter mass",
        "year": 2000,
        "powertrain": [
            "PHEV-c-d",
            "PHEV-e",
            "BEV",
            "FCEV",
            "PHEV-c-p"
        ],
        "sizes": [
            "Mini",
            "Small",
            "Lower medium",
            "Medium",
            "Large",
            "Van",
            "Medium SUV",
            "Large SUV",
            "Micro"
        ],
        "amount": 4.5,
        "loc": 4.5,
        "minimum": 4,
        "maximum": 6,
        "kind": "distribution",
        "uncertainty_type": 5,
        "category": "Powertrain",
        "source": "Del Duce et al (2016)",
        "comment": ""
    },
```

Of course, we could represent this in tabulated format also:

| name | year | powertrain | sizes | amount | ... |
| ---- | ---- | ---------- | ----- | ------ | --- |
| converter mass | 2000 | PHEV-c-d | Mini | 4.5 | ... |

In the instantiation of the [`class VehicleInputParameters(NamedParameters)`](https://github.com/romainsacchi/carculator/blob/7a72499e9bee1231c280628515641cb60342d640/carculator/car_input_parameters.py#L29) >> [`class VehicleInputParameters(NamedParameters)`](https://github.com/romainsacchi/carculator_utils/blob/bbcab4a4308adc7daabf4d0e9ecc9c78834fca51/carculator_utils/vehicle_input_parameters.py#L16) this data is then converted into an [`xarray.DataArray`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.html) with dimensions:

```
  * size        (size) <U12 'Large' 'Large SUV' 'Lower medium' ... 'Small' 'Van'
  * powertrain  (powertrain) <U8 'BEV' 'FCEV' 'HEV-d' ... 'PHEV-e' 'PHEV-p'
  * parameter   (parameter) <U64 '1-Pentene direct emissions, rural' ... 'tra...
  * year        (year) int64 2000 2010 2020 2030 2040 2050
  * value       (value) int64 0
```

(where `value` is relevant to stochastic calculations only).

This array is then used further on [in the `model` library](https://github.com/romainsacchi/carculator/blob/master/carculator/model.py) to perform calculations.

From what I can see, data is extracted from the `DataArray` using [the slicing](https://docs.xarray.dev/en/latest/user-guide/indexing.html) methods.

...so why can't we do this with a Pandas DataFrame?

**Comment by iamsiddhantsahu** [comment]
I wrote a script [b218c47](https://github.com/sustainableaviation/EcoPyLot/commit/b218c473c9efbdea2ac315a733a9a7b02a6d8d0c) to test the memory usage and slicing times comparing Pandas and XArray with sparse arrays.

Here is the plot.
![pandas-vs-xarray](https://github.com/sustainableaviation/EcoPyLot/assets/28495849/1649cf37-c25c-4666-b53b-e2ca42cac08c)

Findings:
1. _Memory_ -- XArray is more memory efficient for sparse arrays than Pandas.
2. _Slicing TIme_ -- Both XArray and Pandas seems to have the same slicing time.

**Comment by michaelweinold** [comment]
`dataset size` is a poor metric. The question was primarily on the _number of dimensions_, so you should have made that explicit in your plot. Just comparing the dataset size is not helpful at all.

Also, you still have to think about the _utility_ of using an `xr.DataArray` vs a `pd.DataFrame`. Is there any operation (eg. slicing, etc.) that we could not do with a DataFrame?

**Comment by iamsiddhantsahu** [comment]
The [pandas.DataFrame.to_xarray()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_xarray.html) function that you are using [here](https://github.com/sustainableaviation/EcoPyLot/blob/xarray-investigation/dev/investigation_xarray.py#L61), converts a [pandas.DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) object to a [xarray.Dataset](https://docs.xarray.dev/en/stable/generated/xarray.Dataset.html) object. And, the `xarray.Dataset` object is a multi-dimensional, **in-memory** array database. It is a dict-like container of labeled arrays ([DataArray](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.html) objects) with aligned dimensions. 

:warning: The important note here is that it is designed as an **in-memory** representation of the data model -- this might be causing memory issues.

**Comment by michaelweinold** [comment]
...what are `Dataset 1`, `2`, `3`? How am I supposed to interpret this figure?
